join:
  fly_in_creative:
    enable: true
  walk_speed: 0.2
  slot_player: 0

fly:
  speed: 0.2
  list_of_ignore_permissions_player:

interaction:
  interact_in_creative:
    enable: true

  options:
    break_blocks: true
    add_blocks: true
    open_doors: false
    open_trapdoors: false
    open_fence_gates: false
    use_buttons: false
    use_levers: false
    interact_item_frames: true
  list_of_ignore_permissions_player:

limits:
  chunk:
    enabled: true
    view-radius: 2
    max-up: 160
    max-down: 32