name: LobbyPlugin
version: '1.0.0'
main: org.astral.lobbyPlugin.LobbyPlugin
api-version: '1.20'
folia-supported: true
authors:
  - duk3lo
  - c127dev


commands:
  lobby:
    description: "Comando principal del plugin"
    usage: "/lobby"
    aliases: [lb]

permissions:
  LobbyPlugin.reload:
    description: "Recargar las Configuraciones del Plugin"
    default: true

  LobbyPlugin.fly:
    description: "Permite volar al jugador"
    default: false

  LobbyPlugin.damage:
    description: "Permite el daño"
    default: false

  LobbyPlugin.interaction:
    description: "Permite al jugador interactuar"
    default: false